version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - db  # Ensure the db service starts before the web service

  db:
    image: postgres:13  # Use the official PostgreSQL image
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist the database data
    environment:
      POSTGRES_USER: ${DATABASE_USER}  # Environment variable for DB username
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}  # Environment variable for DB password
      POSTGRES_DB: ${DATABASE_NAME}  # Database name
    ports:
      - "5433:5432"  # Expose port 5432 for PostgreSQL connection

volumes:
  postgres_data:  # Define a named volume to persist data

networks:
  app_network:
    driver: bridge